-- Migration for Supabase: Finance Module (Proforma Invoices)

CREATE TABLE IF NOT EXISTS proforma_invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pi_number TEXT NOT NULL UNIQUE,
  bill_number TEXT,
  pi_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  bill_date TIMESTAMPTZ,
  recipient_id BIGINT REFERENCES recipients(id),
  applicant_name TEXT NOT NULL,
  applicant_address TEXT,
  beneficiary_name TEXT NOT NULL DEFAULT 'K.A. DESIGN ACCESSORIES LTD.',
  beneficiary_address TEXT DEFAULT '356/1, BLOCK-B, TEK KATHORA, SALNA, GAZIPUR-1703, BANGLADESH',
  beneficiary_bin TEXT DEFAULT '',
  bank_details TEXT DEFAULT 'UNITED COMMERCIAL BANK PLC.
TONGI BRANCH
18, S.K. MANNAN TOWER, CHERAG ALI
GAZIPUR-1712, BANGLADESH
SWIFT CODE: UCBLBDDHTNG',
  buyer TEXT,
  challan_ids JSONB DEFAULT '[]'::jsonb,
  challan_numbers TEXT,
  currency TEXT DEFAULT 'USD',
  currency_symbol TEXT DEFAULT '$',
  total_quantity NUMERIC DEFAULT 0,
  total_amount NUMERIC DEFAULT 0,
  amount_in_words TEXT,
  net_weight TEXT DEFAULT '250 KGS',
  gross_weight TEXT DEFAULT '260 KGS',
  terms_conditions TEXT DEFAULT 'CASH ON DELIVERY.',
  prepared_by TEXT DEFAULT 'Md. Ariful Rahman
Accounts & Admin
K. A. Design Accessories Ltd.',
  authorized_by TEXT DEFAULT 'Maksudha Akter Kumu
Chairman
K.A. DESIGN ACCESSORIES LTD.',
  accepted_by TEXT,
  status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'CANCELLED', 'PAID')),
  notes TEXT,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pi_number ON proforma_invoices(pi_number);
CREATE INDEX IF NOT EXISTS idx_pi_date ON proforma_invoices(pi_date);
CREATE INDEX IF NOT EXISTS idx_pi_recipient ON proforma_invoices(recipient_id);

CREATE TABLE IF NOT EXISTS proforma_invoice_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pi_id BIGINT NOT NULL REFERENCES proforma_invoices(id) ON DELETE CASCADE,
  sl_no INTEGER NOT NULL,
  challan_id BIGINT REFERENCES challans(id),
  item_id BIGINT REFERENCES items(id),
  item_description TEXT NOT NULL,
  po_style_no TEXT,
  quantity NUMERIC NOT NULL DEFAULT 0,
  unit TEXT NOT NULL DEFAULT 'PCS',
  unit_price NUMERIC NOT NULL DEFAULT 0,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_pi_items_pi ON proforma_invoice_items(pi_id);

-- Enable RLS
ALTER TABLE proforma_invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE proforma_invoice_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations on proforma_invoices for authenticated and anon" 
ON proforma_invoices FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow all operations on proforma_invoice_items for authenticated and anon" 
ON proforma_invoice_items FOR ALL USING (true) WITH CHECK (true);
