-- SQL Script to set up Issue & Return Module in Supabase
-- Run this in your Supabase SQL Editor

-- 1. Recipients Table
CREATE TABLE IF NOT EXISTS recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL CHECK (type IN ('FACTORY', 'EMPLOYEE')),
  contact_info TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Issues Table
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id TEXT NOT NULL UNIQUE,
  issue_type TEXT NOT NULL CHECK (issue_type IN ('FACTORY', 'EMPLOYEE')),
  recipient_id BIGINT NOT NULL REFERENCES recipients(id),
  recipient_name TEXT NOT NULL,
  issue_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expected_return_date TIMESTAMP WITH TIME ZONE,
  remarks TEXT,
  attachment_path TEXT,
  is_returnable BOOLEAN NOT NULL DEFAULT TRUE,
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PARTIAL', 'RETURNED')),
  created_by BIGINT REFERENCES users(id),
  produced_item_id BIGINT REFERENCES items(id),
  produced_item_ids TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Issue Items Table
CREATE TABLE IF NOT EXISTS issue_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES items(id),
  quantity DECIMAL NOT NULL CHECK (quantity > 0),
  returned_quantity DECIMAL NOT NULL DEFAULT 0,
  damage_quantity DECIMAL NOT NULL DEFAULT 0,
  rejected_quantity DECIMAL NOT NULL DEFAULT 0,
  unit TEXT NOT NULL,
  style_no TEXT,
  order_number TEXT,
  purchase_no TEXT,
  notes TEXT
);

-- 4. Returns Table
CREATE TABLE IF NOT EXISTS returns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id),
  return_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  remarks TEXT,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Return Items Table
CREATE TABLE IF NOT EXISTS return_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  return_id BIGINT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  issue_item_id BIGINT NOT NULL REFERENCES issue_items(id),
  returned_quantity DECIMAL NOT NULL DEFAULT 0,
  damage_quantity DECIMAL NOT NULL DEFAULT 0,
  rejected_quantity DECIMAL NOT NULL DEFAULT 0,
  notes TEXT
);

-- 6. Factory Production Table
CREATE TABLE IF NOT EXISTS factory_production (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  issue_id BIGINT NOT NULL REFERENCES issues(id),
  product_item_id BIGINT REFERENCES items(id),
  product_name TEXT NOT NULL,
  production_quantity DECIMAL NOT NULL DEFAULT 0,
  wastage_quantity DECIMAL NOT NULL DEFAULT 0,
  balance_quantity DECIMAL NOT NULL DEFAULT 0,
  consumed_items TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed initial recipients (optional)
INSERT INTO recipients (name, type) VALUES ('Factory A', 'FACTORY') ON CONFLICT DO NOTHING;
INSERT INTO recipients (name, type) VALUES ('Factory B', 'FACTORY') ON CONFLICT DO NOTHING;
INSERT INTO recipients (name, type) VALUES ('John Doe', 'EMPLOYEE') ON CONFLICT DO NOTHING;
INSERT INTO recipients (name, type) VALUES ('Jane Smith', 'EMPLOYEE') ON CONFLICT DO NOTHING;

-- Enable RLS (Recommended for Supabase)
ALTER TABLE recipients ENABLE ROW LEVEL SECURITY;
ALTER TABLE issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE issue_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE returns ENABLE ROW LEVEL SECURITY;
ALTER TABLE return_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE factory_production ENABLE ROW LEVEL SECURITY;

-- Add basic public access policies (Adjust according to your security needs)
CREATE POLICY "Enable all for authenticated users" ON recipients FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON issues FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON issue_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON returns FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON return_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON factory_production FOR ALL USING (auth.role() = 'authenticated');
