-- SQL Script to set up Requisition Module in Supabase
-- Run this in your Supabase SQL Editor

-- 1. Requisitions Table
CREATE TABLE IF NOT EXISTS requisitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requisition_no TEXT NOT NULL UNIQUE,
  recipient_id BIGINT REFERENCES recipients(id),
  requester_name TEXT,
  department TEXT,
  purpose TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING'
    CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED')),
  requested_by TEXT,
  approved_by TEXT,
  notes TEXT,
  requisition_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. Requisition Items Table
CREATE TABLE IF NOT EXISTS requisition_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requisition_id BIGINT NOT NULL REFERENCES requisitions(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES items(id),
  requested_quantity DECIMAL NOT NULL CHECK (requested_quantity > 0),
  approved_quantity DECIMAL NOT NULL DEFAULT 0,
  issued_quantity DECIMAL NOT NULL DEFAULT 0,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_requisition_items_req ON requisition_items(requisition_id);

-- 3. Enable RLS
ALTER TABLE requisitions ENABLE ROW LEVEL SECURITY;
ALTER TABLE requisition_items ENABLE ROW LEVEL SECURITY;

-- 4. Basic access policies
CREATE POLICY "Enable all for authenticated users" ON requisitions
  FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON requisition_items
  FOR ALL USING (auth.role() = 'authenticated');

-- 5. Settings
INSERT INTO settings (key, value) VALUES ('requisition_prefix', 'REQ') ON CONFLICT (key) DO NOTHING;
INSERT INTO settings (key, value) VALUES ('require_requisition_approval', 'false') ON CONFLICT (key) DO NOTHING;
