-- SQL Script to update Supabase schema for Warehouses and Barcodes
-- Run this in your Supabase SQL Editor

-- 1. Add barcode_data to items table
ALTER TABLE items ADD COLUMN IF NOT EXISTS barcode_data TEXT;

-- 2. Create warehouses table
CREATE TABLE IF NOT EXISTS warehouses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  address TEXT,
  is_default BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create warehouse_stock table
CREATE TABLE IF NOT EXISTS warehouse_stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  warehouse_id BIGINT NOT NULL REFERENCES warehouses(id) ON DELETE CASCADE,
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  quantity DECIMAL NOT NULL DEFAULT 0,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(warehouse_id, item_id)
);

-- 4. Insert Default Warehouse
INSERT INTO warehouses (name, code, address, is_default, is_active) 
VALUES ('Main Warehouse', 'WH-MAIN', 'Main Office', TRUE, TRUE)
ON CONFLICT (code) DO NOTHING;

-- Enable RLS for the new tables
ALTER TABLE warehouses ENABLE ROW LEVEL SECURITY;
ALTER TABLE warehouse_stock ENABLE ROW LEVEL SECURITY;

-- Add basic public access policies (Adjust according to your security needs)
CREATE POLICY "Enable all for authenticated users" ON warehouses FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON warehouse_stock FOR ALL USING (auth.role() = 'authenticated');
