-- Migration: Add item_price_tiers table and stock_transactions price columns
-- Run this in your Supabase SQL Editor

-- 1. Create item_price_tiers table
CREATE TABLE IF NOT EXISTS item_price_tiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  quantity NUMERIC NOT NULL DEFAULT 0,
  unit_price NUMERIC NOT NULL DEFAULT 0,
  currency TEXT DEFAULT 'BDT',
  conversion_rate NUMERIC DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_item_price_tiers_item_id ON item_price_tiers(item_id);

-- 2. Add price columns to stock_transactions
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS unit_price NUMERIC DEFAULT NULL;
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'BDT';
ALTER TABLE stock_transactions ADD COLUMN IF NOT EXISTS conversion_rate NUMERIC DEFAULT NULL;

-- 3. Enable RLS and add public access policies (matches anon access pattern)
ALTER TABLE item_price_tiers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable all access for item_price_tiers" ON item_price_tiers;
CREATE POLICY "Enable all access for item_price_tiers" ON item_price_tiers FOR ALL USING (true) WITH CHECK (true);

-- 4. Backfill existing items where current_stock > 0 into item_price_tiers
INSERT INTO item_price_tiers (item_id, quantity, unit_price, currency, conversion_rate)
SELECT id, current_stock, COALESCE(unit_price, 0), COALESCE(currency, 'BDT'), conversion_rate
FROM items
WHERE current_stock > 0
  AND id NOT IN (SELECT DISTINCT item_id FROM item_price_tiers);
